/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package streaming.swing;

import javax.swing.JDialog;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import streaming.entity.Serie;
import streaming.service.SerieService;

/**
 *
 * @author admin
 */
@Component
public class JPannelListeSerie extends javax.swing.JPanel {

    /**
     * Creates new form JPannelListeFilm
     */
    @Autowired
    TableModelListeSerie tableModelListSerie;
    
    @Autowired
    JDialogSerie jDialogSerie;
    
    @Autowired
    SerieService serieService;
            
    public JPannelListeSerie() {
        initComponents();
//        rafraichirJTable();
    }
    public void rafraichirJTable(){
        jtSeries.setModel(tableModelListSerie);
        jtSeries.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jBNouvelleSerie = new javax.swing.JButton();
        jBSupprimer = new javax.swing.JButton();
        jtSeri = new javax.swing.JScrollPane();
        jtSeries = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        jBNouvelleSerie.setText(" Nouvelle Serie");
        jBNouvelleSerie.setFocusable(false);
        jBNouvelleSerie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBNouvelleSerie.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBNouvelleSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNouvelleSerieActionPerformed(evt);
            }
        });
        jToolBar1.add(jBNouvelleSerie);

        jBSupprimer.setText("Supprimer");
        jBSupprimer.setFocusable(false);
        jBSupprimer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBSupprimer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSupprimerActionPerformed(evt);
            }
        });
        jToolBar1.add(jBSupprimer);

        add(jToolBar1, java.awt.BorderLayout.NORTH);

        jtSeries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtSeri.setViewportView(jtSeries);

        add(jtSeri, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jBNouvelleSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNouvelleSerieActionPerformed
        jDialogSerie.setJpSeries(this);
        jDialogSerie.setVisible(true);
    }//GEN-LAST:event_jBNouvelleSerieActionPerformed

    private void jBSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSupprimerActionPerformed
                int i=jtSeries.getSelectedRow();
        if(i==-1)
            return;
        
        Long l = (Long) jtSeries.getModel().getValueAt(i, 0);
        
        Serie r = serieService.rechSerie(l);
        serieService.supprimer(r);
        this.rafraichirJTable();
    }//GEN-LAST:event_jBSupprimerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBNouvelleSerie;
    private javax.swing.JButton jBSupprimer;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JScrollPane jtSeri;
    private javax.swing.JTable jtSeries;
    // End of variables declaration//GEN-END:variables
}
