/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package streaming.swing;

import javax.swing.JDialog;
import javax.swing.JScrollPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import streaming.entity.Genre;
import streaming.service.GenreService;

/**
 *
 * @author admin
 */
@Component
public class JPannelListeGenre extends javax.swing.JPanel {
    
    @Autowired
    JDialogGenre jDialogGenre;
    @Autowired
    GenreService genreService;
    @Autowired
    TableModelListGenre tableModelListeGenre;
    /**
     * Creates new form JPannelListeFilm
     */
    public JPannelListeGenre() {
        initComponents();
//        rafraichirJTableGenre();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    public void rafraichirJTableGenre(){
        jtGenre.setModel(tableModelListeGenre);
        jtGenre.repaint();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jBNouveauGenre = new javax.swing.JButton();
        jBSupprimerGenre = new javax.swing.JButton();
        jtGenres = new javax.swing.JScrollPane();
        jtGenre = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        jBNouveauGenre.setText(" Nouveau Genre");
        jBNouveauGenre.setFocusable(false);
        jBNouveauGenre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBNouveauGenre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBNouveauGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNouveauGenreActionPerformed(evt);
            }
        });
        jToolBar1.add(jBNouveauGenre);

        jBSupprimerGenre.setText("Supprimer");
        jBSupprimerGenre.setFocusable(false);
        jBSupprimerGenre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBSupprimerGenre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBSupprimerGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSupprimerGenreActionPerformed(evt);
            }
        });
        jToolBar1.add(jBSupprimerGenre);

        add(jToolBar1, java.awt.BorderLayout.NORTH);

        jtGenre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Genre"
            }
        ));
        jtGenres.setViewportView(jtGenre);

        add(jtGenres, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jBNouveauGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNouveauGenreActionPerformed
        jDialogGenre.setModal(true);
        jDialogGenre.setJpGenre(this);
        jDialogGenre.setVisible(true);
    }//GEN-LAST:event_jBNouveauGenreActionPerformed

    private void jBSupprimerGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSupprimerGenreActionPerformed
        
        int i = jtGenre.getSelectedRow();
        
        if (i == -1) {
            return;
        } 
        else {
            Long l = (Long) jtGenre.getModel().getValueAt(i, 0);
            Genre g = genreService.rechercheGenre(l);
            genreService.supprimer(g);
            this.rafraichirJTableGenre();
        }

    }//GEN-LAST:event_jBSupprimerGenreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBNouveauGenre;
    private javax.swing.JButton jBSupprimerGenre;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable jtGenre;
    private javax.swing.JScrollPane jtGenres;
    // End of variables declaration//GEN-END:variables
}
