/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package streaming.swing;

import javax.swing.JDialog;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import streaming.entity.Film;
import streaming.service.FilmService;

/**
 *
 * @author admin
 */
@Component
public class JPannelListeFilm extends javax.swing.JPanel {

    @Autowired
    FilmService filmService;
    
    @Autowired
    TableModelListeFilm tablemodelListeFilm;
    
    @Autowired
    JDialogFilm jDialogFilm;
    
    /**
     * Creates new form JPannelListeFilm
     */
    public JPannelListeFilm() {
        initComponents();
//        this.rafraichirJTable();
    }
    
    public void rafraichirJTable(){
        jtFilm.setModel(tablemodelListeFilm);
        jtFilm.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jBNouveauFilm = new javax.swing.JButton();
        jBSupprimer = new javax.swing.JButton();
        jtFilms = new javax.swing.JScrollPane();
        jtFilm = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        jBNouveauFilm.setText(" Nouveau Film");
        jBNouveauFilm.setFocusable(false);
        jBNouveauFilm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBNouveauFilm.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBNouveauFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNouveauFilmActionPerformed(evt);
            }
        });
        jToolBar1.add(jBNouveauFilm);

        jBSupprimer.setText("Supprimer");
        jBSupprimer.setFocusable(false);
        jBSupprimer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBSupprimer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSupprimerActionPerformed(evt);
            }
        });
        jToolBar1.add(jBSupprimer);

        add(jToolBar1, java.awt.BorderLayout.NORTH);

        jtFilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtFilms.setViewportView(jtFilm);

        add(jtFilms, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jBSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSupprimerActionPerformed
        int i=jtFilm.getSelectedRow();
        if(i==-1)
            return;
        
        Long l = (Long) jtFilm.getModel().getValueAt(i, 0);
        Film f = filmService.rechercheFilm(l);
        filmService.supprimer(f);
        this.rafraichirJTable();
    }//GEN-LAST:event_jBSupprimerActionPerformed

    private void jBNouveauFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNouveauFilmActionPerformed
        
        jDialogFilm.setJpFilm(this);
        jDialogFilm.setVisible(true);
    }//GEN-LAST:event_jBNouveauFilmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBNouveauFilm;
    private javax.swing.JButton jBSupprimer;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable jtFilm;
    private javax.swing.JScrollPane jtFilms;
    // End of variables declaration//GEN-END:variables
}
