/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package streaming.swing;

import javax.swing.JDialog;
import streaming.entity.Genre;
import streaming.service.GenreService;

/**
 *
 * @author admin
 */
public class JPannelListeGenre extends javax.swing.JPanel {
    
    private GenreService gs = new GenreService();
    /**
     * Creates new form JPannelListeFilm
     */
    public JPannelListeGenre() {
        initComponents();
        rafraichirJTableGenre();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void rafraichirJTableGenre(){
        jTable_Genre.setModel(new TableModelListGenre());
        jtGenre.repaint();
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jBNouveauGenre = new javax.swing.JButton();
        jBSupprimerGenre = new javax.swing.JButton();
        jtGenre = new javax.swing.JScrollPane();
        jTable_Genre = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        jBNouveauGenre.setText(" Nouveau Genre");
        jBNouveauGenre.setFocusable(false);
        jBNouveauGenre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBNouveauGenre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBNouveauGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNouveauGenreActionPerformed(evt);
            }
        });
        jToolBar1.add(jBNouveauGenre);

        jBSupprimerGenre.setText("Supprimer");
        jBSupprimerGenre.setFocusable(false);
        jBSupprimerGenre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBSupprimerGenre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBSupprimerGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSupprimerGenreActionPerformed(evt);
            }
        });
        jToolBar1.add(jBSupprimerGenre);

        add(jToolBar1, java.awt.BorderLayout.NORTH);

        jTable_Genre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Genre"
            }
        ));
        jtGenre.setViewportView(jTable_Genre);

        add(jtGenre, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jBNouveauGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNouveauGenreActionPerformed
        JDialog dlgG = new JDialogGenre(null, true, this);
        dlgG.setVisible(true);
    }//GEN-LAST:event_jBNouveauGenreActionPerformed

    private void jBSupprimerGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSupprimerGenreActionPerformed
        
        int i = jTable_Genre.getSelectedRow();
        
        if (i == -1) {
            return;
        } 
        else {
            Long l = (Long) jTable_Genre.getModel().getValueAt(i, 0);
            Genre g = gs.rechercheGenre(l);
            gs.supprimer(g);
            this.rafraichirJTableGenre();
        }

    }//GEN-LAST:event_jBSupprimerGenreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBNouveauGenre;
    private javax.swing.JButton jBSupprimerGenre;
    private javax.swing.JTable jTable_Genre;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JScrollPane jtGenre;
    // End of variables declaration//GEN-END:variables
}
